# Generated by Django 3.2.5 on 2023-02-17 02:46

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('comentario', models.TextField()),
                ('imagen', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[800, 600], upload_to='comentarios/')),
            ],
        ),
    ]
