# Generated by Django 3.2.5 on 2023-02-17 04:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0003_alter_comentario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[800, 600], upload_to='static/img'),
        ),
    ]
