# Generated by Django 3.2.5 on 2023-02-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0007_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='userAdmin.comentario'),
        ),
    ]
